### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by Jmagicc** [ibclabs/omnilayer-go#1]
omniClient :=omnilayer.New(conf)
	balance,err := omniClient.OmniGetBalance(command)
	if err != nil {
		log.Fatal("OmniGetBalance :",err)
		c.JSON(http.StatusOK,Tools.NewBaseReturn(0,err.Error(),""))
		return
	}

[GIN-debug] Listening and serving HTTP on :8988
2021/09/29 17:11:04 OmniGetBalance :-32601: Method not found
exit status 1

????why

**Comment by avid** [comment]
Sorry, there is no answer. Project is not maintained for more than 2 years.
